const GamesDB =  JSON.parse(`[
  {
    "id": 540,
    "title": "Overwatch 2",
    "thumbnail": "https://www.freetogame.com/g/540/thumbnail.jpg",
    "short_description": "A hero-focused first-person team shooter from Blizzard Entertainment.",
    "game_url": "https://www.freetogame.com/open/overwatch-2",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Activision Blizzard",
    "developer": "Blizzard Entertainment",
    "release_date": "2022-10-04",
    "freetogame_profile_url": "https://www.freetogame.com/overwatch-2"
  },
  {
    "id": 516,
    "title": "PUBG: BATTLEGROUNDS",
    "thumbnail": "https://www.freetogame.com/g/516/thumbnail.jpg",
    "short_description": "Get into the action in one of the longest running battle royale games PUBG Battlegrounds.",
    "game_url": "https://www.freetogame.com/open/pubg",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "KRAFTON, Inc.",
    "developer": "KRAFTON, Inc.",
    "release_date": "2022-01-12",
    "freetogame_profile_url": "https://www.freetogame.com/pubg"
  },
  {
    "id": 508,
    "title": "Enlisted",
    "thumbnail": "https://www.freetogame.com/g/508/thumbnail.jpg",
    "short_description": "Get ready to command your own World War II military squad in Gaijin and Darkflow Softwares MMO squad-based shooter Enlisted. ",
    "game_url": "https://www.freetogame.com/open/enlisted",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Gaijin Entertainment",
    "developer": "Darkflow Software",
    "release_date": "2021-04-08",
    "freetogame_profile_url": "https://www.freetogame.com/enlisted"
  },
  {
    "id": 380,
    "title": "Dark Orbit Reloaded",
    "thumbnail": "https://www.freetogame.com/g/380/thumbnail.jpg",
    "short_description": "A browser-based 3D space-combat MMO with a massive playerbase!",
    "game_url": "https://www.freetogame.com/open/darkorbit",
    "genre": "Shooter",
    "platform": "Web Browser",
    "publisher": "Bigpoint",
    "developer": "Bigpoint",
    "release_date": "2006-12-11",
    "freetogame_profile_url": "https://www.freetogame.com/darkorbit"
  },
  {
    "id": 515,
    "title": "Halo Infinite",
    "thumbnail": "https://www.freetogame.com/g/515/thumbnail.jpg",
    "short_description": "For the first time ever, a free-to-play Halo experience is available in the form of Halo Infinites multiplayer.",
    "game_url": "https://www.freetogame.com/open/halo-infinite",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Xbox Game Studios",
    "developer": "343 Industries",
    "release_date": "2021-11-15",
    "freetogame_profile_url": "https://www.freetogame.com/halo-infinite"
  },
  {
    "id": 5,
    "title": "Crossout",
    "thumbnail": "https://www.freetogame.com/g/5/thumbnail.jpg",
    "short_description": "A post-apocalyptic MMO vehicle combat game! ",
    "game_url": "https://www.freetogame.com/open/crossout",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Targem",
    "developer": "Gaijin",
    "release_date": "2017-05-30",
    "freetogame_profile_url": "https://www.freetogame.com/crossout"
  },
  {
    "id": 9,
    "title": "World of Warships",
    "thumbnail": "https://www.freetogame.com/g/9/thumbnail.jpg",
    "short_description": "A 3D free to play naval action-themed MMO from the creators of World of Tanks! ",
    "game_url": "https://www.freetogame.com/open/world-of-warships",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Wargaming",
    "developer": "Wargaming",
    "release_date": "2015-07-02",
    "freetogame_profile_url": "https://www.freetogame.com/world-of-warships"
  },
  {
    "id": 12,
    "title": "War Thunder",
    "thumbnail": "https://www.freetogame.com/g/12/thumbnail.jpg",
    "short_description": "A MMO shooter that puts you in command of hundreds of the finest combat vehicles of World War II.",
    "game_url": "https://www.freetogame.com/open/war-thunder",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Gaijin Entertainment",
    "developer": "Gaijin Entertainment",
    "release_date": "2013-08-15",
    "freetogame_profile_url": "https://www.freetogame.com/war-thunder"
  },
  {
    "id": 2,
    "title": "World of Tanks",
    "thumbnail": "https://www.freetogame.com/g/2/thumbnail.jpg",
    "short_description": "If you like blowing up tanks, with a quick and intense game style you will love this game!",
    "game_url": "https://www.freetogame.com/open/world-of-tanks",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Wargaming",
    "developer": "Wargaming",
    "release_date": "2011-04-12",
    "freetogame_profile_url": "https://www.freetogame.com/world-of-tanks"
  },
  {
    "id": 466,
    "title": "Valorant",
    "thumbnail": "https://www.freetogame.com/g/466/thumbnail.jpg",
    "short_description": "Test your mettle in Riot Games character-based FPS shooter Valorant.",
    "game_url": "https://www.freetogame.com/open/valorant",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Riot Games",
    "developer": "Riot Games",
    "release_date": "2020-06-02",
    "freetogame_profile_url": "https://www.freetogame.com/valorant"
  },
  {
    "id": 452,
    "title": "Call Of Duty: Warzone",
    "thumbnail": "https://www.freetogame.com/g/452/thumbnail.jpg",
    "short_description": "A standalone free-to-play battle royale and modes accessible via Call of Duty: Modern Warfare.",
    "game_url": "https://www.freetogame.com/open/call-of-duty-warzone",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Activision",
    "developer": "Infinity Ward",
    "release_date": "2020-03-10",
    "freetogame_profile_url": "https://www.freetogame.com/call-of-duty-warzone"
  },
  {
    "id": 21,
    "title": "Destiny 2",
    "thumbnail": "https://www.freetogame.com/g/21/thumbnail.jpg",
    "short_description": "A free-to-play multiplayer Sci-Fi MMOFPS from Bungie.",
    "game_url": "https://www.freetogame.com/open/destiny-2",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Bungie",
    "developer": "Bungie",
    "release_date": "2019-10-01",
    "freetogame_profile_url": "https://www.freetogame.com/destiny-2"
  },
  {
    "id": 23,
    "title": "Apex Legends",
    "thumbnail": "https://www.freetogame.com/g/23/thumbnail.jpg",
    "short_description": "A free-to-play strategic battle royale game featuring 60-player matches and team-based play. ",
    "game_url": "https://www.freetogame.com/open/apex-legends",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Electronic Arts",
    "developer": "Electronic Arts",
    "release_date": "2019-02-04",
    "freetogame_profile_url": "https://www.freetogame.com/apex-legends"
  },
  {
    "id": 57,
    "title": "Fortnite",
    "thumbnail": "https://www.freetogame.com/g/57/thumbnail.jpg",
    "short_description": "A free-to-play, standalone mode of Epic Game's Fortnite. ",
    "game_url": "https://www.freetogame.com/open/fortnite-battle-royale",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Epic Games",
    "developer": "Epic Games",
    "release_date": "2017-09-26",
    "freetogame_profile_url": "https://www.freetogame.com/fortnite-battle-royale"
  },
  {
    "id": 202,
    "title": "Heroes & Generals",
    "thumbnail": "https://www.freetogame.com/g/202/thumbnail.jpg",
    "short_description": "A World War II-based MMOFPS that mixes infantry, armor, and aircraft.",
    "game_url": "https://www.freetogame.com/open/heroes-and-generals",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Reto-Moto",
    "developer": "Reto-Moto",
    "release_date": "2014-07-11",
    "freetogame_profile_url": "https://www.freetogame.com/heroes-and-generals"
  },
  {
    "id": 207,
    "title": "Warface",
    "thumbnail": "https://www.freetogame.com/g/207/thumbnail.jpg",
    "short_description": "A free-to-play multiplayer online FPS from Crytek, makers of the Far Cry and Crysis series of games.",
    "game_url": "https://www.freetogame.com/open/warface",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Crytek",
    "developer": "Crytek",
    "release_date": "2014-07-01",
    "freetogame_profile_url": "https://www.freetogame.com/warface"
  },
  {
    "id": 3,
    "title": "Warframe",
    "thumbnail": "https://www.freetogame.com/g/3/thumbnail.jpg",
    "short_description": "A cooperative free-to-play third person online action shooter set in an stunning sci-fi world. ",
    "game_url": "https://www.freetogame.com/open/warframe",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Digital Extremes",
    "developer": "Digital Extremes",
    "release_date": "2013-03-25",
    "freetogame_profile_url": "https://www.freetogame.com/warframe"
  },
  {
    "id": 243,
    "title": "PlanetSide 2",
    "thumbnail": "https://www.freetogame.com/g/243/thumbnail.jpg",
    "short_description": "A free-to-play open-world FPS that pits three factions against each other in a never-ending war.",
    "game_url": "https://www.freetogame.com/open/planetside-2",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Daybreak Games",
    "developer": "Daybreak Games",
    "release_date": "2012-11-21",
    "freetogame_profile_url": "https://www.freetogame.com/planetside-2"
  },
  {
    "id": 564,
    "title": "Synced",
    "thumbnail": "https://www.freetogame.com/g/564/thumbnail.jpg",
    "short_description": "A free-to-play co-op sci-fi shooter.",
    "game_url": "https://www.freetogame.com/open/synced",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Level Infinite",
    "developer": "NExT Studios",
    "release_date": "2023-09-07",
    "freetogame_profile_url": "https://www.freetogame.com/synced"
  },
  {
    "id": 567,
    "title": "Microvolts: Recharged",
    "thumbnail": "https://www.freetogame.com/g/567/thumbnail.jpg",
    "short_description": "A lobby-based third-person shooter with a toy-theme.",
    "game_url": "https://www.freetogame.com/open/microvolts",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Masangsoft",
    "developer": "Masangsoft",
    "release_date": "2023-09-08",
    "freetogame_profile_url": "https://www.freetogame.com/microvolts"
  },
  {
    "id": 558,
    "title": "Hawked",
    "thumbnail": "https://www.freetogame.com/g/558/thumbnail.jpg",
    "short_description": "A free-to-play PvPvE treasure hunting shooter.",
    "game_url": "https://www.freetogame.com/open/hawked",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "My.Games",
    "developer": "My.Games",
    "release_date": "2023-08-03",
    "freetogame_profile_url": "https://www.freetogame.com/hawked"
  },
  {
    "id": 554,
    "title": "Undawn",
    "thumbnail": "https://www.freetogame.com/g/554/thumbnail.jpg",
    "short_description": "A free-to-play open-world survival RPG developed by LightSpeed studios and published by Level Infinite.",
    "game_url": "https://www.freetogame.com/open/undawn",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Level Infinite",
    "developer": "LightSpeed Studios",
    "release_date": "2023-06-15",
    "freetogame_profile_url": "https://www.freetogame.com/undawn"
  },
  {
    "id": 551,
    "title": "Veiled Experts",
    "thumbnail": "https://www.freetogame.com/g/551/thumbnail.jpg",
    "short_description": "A free-to-play multiplayer shooter game focused on the search and destroy mode of classic shooters.",
    "game_url": "https://www.freetogame.com/open/veiled-experts",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Nexon Games Co., LTC",
    "developer": "Nexon",
    "release_date": "2023-05-18",
    "freetogame_profile_url": "https://www.freetogame.com/veiled-experts"
  },
  {
    "id": 548,
    "title": "Dead Cide Club",
    "thumbnail": "https://www.freetogame.com/g/548/thumbnail.jpg",
    "short_description": "A free-to-play, side-scrolling shooter with a variety of modes and character types to choose from.",
    "game_url": "https://www.freetogame.com/open/dead-cide-club",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "PressA",
    "developer": "PressZ",
    "release_date": "2023-02-28",
    "freetogame_profile_url": "https://www.freetogame.com/dead-cide-club"
  },
  {
    "id": 542,
    "title": "World Boss",
    "thumbnail": "https://www.freetogame.com/g/542/thumbnail.jpg",
    "short_description": "An experimental FPS based on io and roguelike gameplay.",
    "game_url": "https://www.freetogame.com/open/world-boss",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Playside",
    "developer": "Playside",
    "release_date": "2022-10-19",
    "freetogame_profile_url": "https://www.freetogame.com/world-boss"
  },
  {
    "id": 537,
    "title": "Gundam Evolution",
    "thumbnail": "https://www.freetogame.com/g/537/thumbnail.jpg",
    "short_description": "A 6v6 team-based shooter based on the Gundam multiverse",
    "game_url": "https://www.freetogame.com/open/gundam-evolution",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Bandai Namco",
    "developer": "Bandai Namco",
    "release_date": "2022-09-21",
    "freetogame_profile_url": "https://www.freetogame.com/gundam-evolution"
  },
  {
    "id": 544,
    "title": "Galahad 3093",
    "thumbnail": "https://www.freetogame.com/g/544/thumbnail.jpg",
    "short_description": "A 12v12 team shooter featuring mechs based on Arthurian legend.",
    "game_url": "https://www.freetogame.com/open/galahad-3093",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Simutronics Corp.",
    "developer": "Simutronics Corp.",
    "release_date": "2022-09-01",
    "freetogame_profile_url": "https://www.freetogame.com/galahad-3093"
  },
  {
    "id": 533,
    "title": "A.V.A Global",
    "thumbnail": "https://www.freetogame.com/g/533/thumbnail.jpg",
    "short_description": "A.V.A is a free-to-play online first-person shooter with multiple game modes, unique customizations, as well as PvP and PvE gameplay.",
    "game_url": "https://www.freetogame.com/open/ava",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "NEOWIZ",
    "developer": "NEOWIZ",
    "release_date": "2022-08-24",
    "freetogame_profile_url": "https://www.freetogame.com/ava"
  },
  {
    "id": 534,
    "title": "Lost Light",
    "thumbnail": "https://www.freetogame.com/g/534/thumbnail.jpg",
    "short_description": "A post-apocalyptic shooter built around creating a realistic experience.",
    "game_url": "https://www.freetogame.com/open/lost-light",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "NetEase Games",
    "developer": "NetEase Games",
    "release_date": "2022-08-04",
    "freetogame_profile_url": "https://www.freetogame.com/lost-light"
  },
  {
    "id": 519,
    "title": "Space Punks",
    "thumbnail": "https://www.freetogame.com/g/519/thumbnail.jpg",
    "short_description": "Space Punks is a sci-fi co-op looter shooter with graphics and humor that will likely appeal to the Borderlands fans among us.",
    "game_url": "https://www.freetogame.com/open/space-punks",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "JAGEX",
    "developer": "Flying Wild Hog",
    "release_date": "2022-04-20",
    "freetogame_profile_url": "https://www.freetogame.com/space-punks"
  },
  {
    "id": 513,
    "title": "Super Squad",
    "thumbnail": "https://www.freetogame.com/g/513/thumbnail.jpg",
    "short_description": "Prepare yourself. Its time for Mayhem. Super Squad is a multi-player online shoot-em-up (or MOSH)!",
    "game_url": "https://www.freetogame.com/open/super-squad",
    "genre": "MOBA",
    "platform": "PC (Windows)",
    "publisher": "Bad Fox Studios",
    "developer": "Bad Fox Studios",
    "release_date": "2021-06-25",
    "freetogame_profile_url": "https://www.freetogame.com/super-squad"
  },
  {
    "id": 512,
    "title": "Sherwood Extreme",
    "thumbnail": "https://www.freetogame.com/g/512/thumbnail.jpg",
    "short_description": "High action arcade shooter Sherwood Extreme sends players on a mission to save the kingdom!",
    "game_url": "https://www.freetogame.com/open/sherwood-extreme",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "CAGE Studios",
    "developer": "CAGE Studios",
    "release_date": "2021-05-12",
    "freetogame_profile_url": "https://www.freetogame.com/sherwood-extreme"
  },
  {
    "id": 510,
    "title": "Drifters Loot the Galaxy",
    "thumbnail": "https://www.freetogame.com/g/510/thumbnail.jpg",
    "short_description": "Grab your Driftpacs and grappling hooks, its time to loot. Pick a character and dive into Blind Squirrel team-based shooter, Drifters Loot the Galaxy.",
    "game_url": "https://www.freetogame.com/open/drifters-loot-the-galaxy",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Blind Squirrel Entertainment",
    "developer": "Blind Squirrel Entertainment",
    "release_date": "2021-04-15",
    "freetogame_profile_url": "https://www.freetogame.com/drifters-loot-the-galaxy"
  },
  {
    "id": 507,
    "title": "Super Mecha Champions",
    "thumbnail": "https://www.freetogame.com/g/507/thumbnail.jpg",
    "short_description": "Super Mecha Champions is a PC port of the mobile anime PvP game from NetEease, featuring a variety of modes but focusing on battle royale.",
    "game_url": "https://www.freetogame.com/open/super-mecha-champions",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "NetEase Games",
    "developer": "NetEase Games",
    "release_date": "2021-03-25",
    "freetogame_profile_url": "https://www.freetogame.com/super-mecha-champions"
  },
  {
    "id": 498,
    "title": "Blankos Block Party",
    "thumbnail": "https://www.freetogame.com/g/498/thumbnail.jpg",
    "short_description": "What happens when you take the vinyl collectible toy experience and combine it with an open-world multiplayer game? You get Blankos Block Party!",
    "game_url": "https://www.freetogame.com/open/blankos",
    "genre": "MMO",
    "platform": "PC (Windows)",
    "publisher": "Third Kind Games",
    "developer": "Mythical Games Inc",
    "release_date": "2020-12-11",
    "freetogame_profile_url": "https://www.freetogame.com/blankos"
  },
  {
    "id": 476,
    "title": "Rogue Company",
    "thumbnail": "https://www.freetogame.com/g/476/thumbnail.jpg",
    "short_description": "From Hi-Rez Studios, the team that brought you Smite and Paladins, comes Rogue Company, a cross-platform, competitive team-based third person shooter.",
    "game_url": "https://www.freetogame.com/open/rogue-company",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Hi-Rez Studios",
    "developer": "First Watch Games",
    "release_date": "2020-10-01",
    "freetogame_profile_url": "https://www.freetogame.com/rogue-company"
  },
  {
    "id": 473,
    "title": "Spellbreak",
    "thumbnail": "https://www.freetogame.com/g/473/thumbnail.jpg",
    "short_description": "Spellbreak is a multiplayer, multi-platform battle-royale where player take on the role of a battlemage mastering elemental magic and using spells to compete against other players.",
    "game_url": "https://www.freetogame.com/open/spellbreak",
    "genre": "Battle Royale",
    "platform": "PC (Windows)",
    "publisher": "Proletariat",
    "developer": "Proletariat",
    "release_date": "2020-09-04",
    "freetogame_profile_url": "https://www.freetogame.com/spellbreak"
  },
  {
    "id": 469,
    "title": "Unfortunate Spacemen",
    "thumbnail": "https://www.freetogame.com/g/469/thumbnail.jpg",
    "short_description": "Unfortunate Spacemen is a co-op multiplayer game about Shapeshifting with a Co-op Story Mode, lots of objectives and more!",
    "game_url": "https://www.freetogame.com/open/unfortunate-spacemen",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "New Blood Interactive",
    "developer": "Geoff 'Zag' Keene",
    "release_date": "2020-06-12",
    "freetogame_profile_url": "https://www.freetogame.com/unfortunate-spacemen"
  },
  {
    "id": 39,
    "title": "Darwin Project",
    "thumbnail": "https://www.freetogame.com/g/39/thumbnail.jpg",
    "short_description": "A free-to-play 10-player battle royale game set just prior to an impeding ice age.",
    "game_url": "https://www.freetogame.com/open/darwin-project",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Scavengers Studio",
    "developer": "Scavengers Studio",
    "release_date": "2020-01-14",
    "freetogame_profile_url": "https://www.freetogame.com/darwin-project"
  },
  {
    "id": 4,
    "title": "CRSED: F.O.A.D.",
    "thumbnail": "https://www.freetogame.com/g/4/thumbnail.jpg",
    "short_description": "Take the battle royale genre and add  mystical powers and you have CRSED: F.O.A.D. (Aka Cuisine Royale: Second Edition)",
    "game_url": "https://www.freetogame.com/open/crsed",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Gaijin Distribution KFT",
    "developer": "Darkflow Software",
    "release_date": "2019-12-12",
    "freetogame_profile_url": "https://www.freetogame.com/crsed"
  },
  {
    "id": 437,
    "title": "Stay Out",
    "thumbnail": "https://www.freetogame.com/g/437/thumbnail.jpg",
    "short_description": "An MMORPG featuring urban exploration and shooter elements.",
    "game_url": "https://www.freetogame.com/open/stay-out",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Mobile Technologies LLC",
    "developer": "Mobile Technologies LLC",
    "release_date": "2019-11-27",
    "freetogame_profile_url": "https://www.freetogame.com/stay-out"
  },
  {
    "id": 20,
    "title": "Splitgate: Arena Warfare",
    "thumbnail": "https://www.freetogame.com/g/20/thumbnail.jpg",
    "short_description": "A free-to-play multiplayer shooter developed and published by 1047 games. ",
    "game_url": "https://www.freetogame.com/open/splitgate-arena-warfare",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "1047 Games",
    "developer": "1047 Games",
    "release_date": "2019-05-22",
    "freetogame_profile_url": "https://www.freetogame.com/splitgate-arena-warfare"
  },
  {
    "id": 68,
    "title": "Dreadnought",
    "thumbnail": "https://www.freetogame.com/g/68/thumbnail.jpg",
    "short_description": "A free-to-play combat flight simulator developed by Yager Development and published by Grey Box. ",
    "game_url": "https://www.freetogame.com/open/dreadnought",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Grey Box",
    "developer": "Yager Development",
    "release_date": "2018-10-14",
    "freetogame_profile_url": "https://www.freetogame.com/dreadnought"
  },
  {
    "id": 299,
    "title": "Combat Arms: Reloaded",
    "thumbnail": "https://www.freetogame.com/g/299/thumbnail.jpg",
    "short_description": "A free to play modern first person shooter with lots of maps and weapons!",
    "game_url": "https://www.freetogame.com/open/combat-arms",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "VALOFE, NEXON",
    "developer": "Doobic Studios",
    "release_date": "2018-10-31",
    "freetogame_profile_url": "https://www.freetogame.com/combat-arms"
  },
  {
    "id": 538,
    "title": "World War 3",
    "thumbnail": "https://www.freetogame.com/g/538/thumbnail.jpg",
    "short_description": "A realistic multiplayer tactical FPS.",
    "game_url": "https://www.freetogame.com/open/world-war-3",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Wishlist Games, The 4 Winds Entertainment",
    "developer": "The Farm 51",
    "release_date": "2018-10-19",
    "freetogame_profile_url": "https://www.freetogame.com/world-war-3"
  },
  {
    "id": 28,
    "title": "Spacelords",
    "thumbnail": "https://www.freetogame.com/g/28/thumbnail.jpg",
    "short_description": "A free-to-play 4v1 sci-fi shooter. ",
    "game_url": "https://www.freetogame.com/open/spacelords",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": " MercurySteam Entertainment",
    "developer": "MercurySteam",
    "release_date": "2018-09-22",
    "freetogame_profile_url": "https://www.freetogame.com/spacelords"
  },
  {
    "id": 282,
    "title": "BlackShot: Revolution",
    "thumbnail": "https://www.freetogame.com/g/282/thumbnail.jpg",
    "short_description": "Get thrown into the fast-paced action of a virtual war zone and compete against other players.",
    "game_url": "https://www.freetogame.com/open/blackshot",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Papaya Play",
    "developer": "Vertigo Games",
    "release_date": "2018-07-27",
    "freetogame_profile_url": "https://www.freetogame.com/blackshot"
  },
  {
    "id": 36,
    "title": "Realm Royale Reforged",
    "thumbnail": "https://www.freetogame.com/g/36/thumbnail.jpg",
    "short_description": "A free-to-play fantasy-themed battle royale game based on Hi-Rez Studio's team shooter Paladins. ",
    "game_url": "https://www.freetogame.com/open/realm-royale",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Hi-Rez Studios",
    "developer": "Hi-Rez Studios",
    "release_date": "2018-06-05",
    "freetogame_profile_url": "https://www.freetogame.com/realm-royale"
  },
  {
    "id": 506,
    "title": "Totally Accurate Battlegrounds",
    "thumbnail": "https://www.freetogame.com/g/506/thumbnail.jpg",
    "short_description": "Take 60 players, throw them on a map together with over 90 weapons, including balloon crossbows, pots and pans, and inflatable hammers, add physics-based parkour and you have Landfalls Totally Accurate Battlegrounds (TABG).",
    "game_url": "https://www.freetogame.com/open/tabg",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Landfall",
    "developer": "Landfall",
    "release_date": "2018-06-06",
    "freetogame_profile_url": "https://www.freetogame.com/tabg"
  },
  {
    "id": 434,
    "title": "Will To Live",
    "thumbnail": "https://www.freetogame.com/g/434/thumbnail.jpg",
    "short_description": "A free-to-play MMORPG-shooter developed and published by AlphaSoft LLC.",
    "game_url": "https://www.freetogame.com/open/will-to-live",
    "genre": "MMORPG",
    "platform": "PC (Windows)",
    "publisher": "AlphaSoft LLC",
    "developer": "AlphaSoft LLC",
    "release_date": "2018-04-05",
    "freetogame_profile_url": "https://www.freetogame.com/will-to-live"
  },
  {
    "id": 43,
    "title": "Z1 Battle Royale",
    "thumbnail": "https://www.freetogame.com/g/43/thumbnail.jpg",
    "short_description": "A highly competitive free-to-play battle royale shooter.",
    "game_url": "https://www.freetogame.com/open/z1-battle-royale",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Daybreak Game Company",
    "developer": "Daybreak Game Company",
    "release_date": "2018-02-28",
    "freetogame_profile_url": "https://www.freetogame.com/z1-battle-royale"
  },
  {
    "id": 48,
    "title": "Ironsight",
    "thumbnail": "https://www.freetogame.com/g/48/thumbnail.jpg",
    "short_description": "A free-to-play futuristic shooter published by Aeria Games. ",
    "game_url": "https://www.freetogame.com/open/ironsight",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Aeria Games",
    "developer": "Wiple Games",
    "release_date": "2018-02-01",
    "freetogame_profile_url": "https://www.freetogame.com/ironsight"
  },
  {
    "id": 58,
    "title": "The Ultimatest Battle",
    "thumbnail": "https://www.freetogame.com/g/58/thumbnail.jpg",
    "short_description": "A free-to-play 2D platform game that pits two teams of players against each other in a variety of modes. ",
    "game_url": "https://www.freetogame.com/open/the-ultimatest-battle",
    "genre": "Fighting",
    "platform": "PC (Windows)",
    "publisher": "Ediogames",
    "developer": "Ediogames",
    "release_date": "2017-09-12",
    "freetogame_profile_url": "https://www.freetogame.com/the-ultimatest-battle"
  },
  {
    "id": 30,
    "title": "Quake Champions",
    "thumbnail": "https://www.freetogame.com/g/30/thumbnail.jpg",
    "short_description": "Quake Champions is a callback to the early days of the Quake IP, featuring the fast-paced action that made the IP popular over two decades ago. ",
    "game_url": "https://www.freetogame.com/open/quake-champions",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Bethesda Softworks",
    "developer": "id Software",
    "release_date": "2017-08-22",
    "freetogame_profile_url": "https://www.freetogame.com/quake-champions"
  },
  {
    "id": 61,
    "title": "Black Squad",
    "thumbnail": "https://www.freetogame.com/g/61/thumbnail.jpg",
    "short_description": "A free-to-play military FPS developed by NS STUDIO and published by NEOWIZ.",
    "game_url": "https://www.freetogame.com/open/black-squad",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "NEOWIZ",
    "developer": "NS Studio",
    "release_date": "2017-07-28",
    "freetogame_profile_url": "https://www.freetogame.com/black-squad"
  },
  {
    "id": 63,
    "title": "Argo",
    "thumbnail": "https://www.freetogame.com/g/63/thumbnail.jpg",
    "short_description": "A tactical first-person shooter from the Arma 3 developer.",
    "game_url": "https://www.freetogame.com/open/argo",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Bohemia Interactive",
    "developer": "Bohemia Interactive",
    "release_date": "2017-06-22",
    "freetogame_profile_url": "https://www.freetogame.com/argo"
  },
  {
    "id": 55,
    "title": "Deceit",
    "thumbnail": "https://www.freetogame.com/g/55/thumbnail.jpg",
    "short_description": "A free-to-play multiplayer first-person shooter set in an asylum! ",
    "game_url": "https://www.freetogame.com/open/deceit",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Automaton",
    "developer": "Automaton",
    "release_date": "2017-05-03",
    "freetogame_profile_url": "https://www.freetogame.com/deceit"
  },
  {
    "id": 67,
    "title": "Awesomenauts",
    "thumbnail": "https://www.freetogame.com/g/67/thumbnail.jpg",
    "short_description": "A 3v3 2D battle arena Developed by Ronimo games.",
    "game_url": "https://www.freetogame.com/open/awesomenauts",
    "genre": "MOBA",
    "platform": "PC (Windows)",
    "publisher": "Ronimo Games",
    "developer": "Ronimo Games",
    "release_date": "2017-05-24",
    "freetogame_profile_url": "https://www.freetogame.com/awesomenauts"
  },
  {
    "id": 70,
    "title": "Alien Swarm: Reactive Drop",
    "thumbnail": "https://www.freetogame.com/g/70/thumbnail.jpg",
    "short_description": "A free-to-play top-down tactical co-op expansion on the Alien swarm game and Source SDK.",
    "game_url": "https://www.freetogame.com/open/alien-swarm-reactive-drop",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Reactive Drop",
    "developer": "Reactive Drop",
    "release_date": "2017-04-20",
    "freetogame_profile_url": "https://www.freetogame.com/alien-swarm-reactive-drop"
  },
  {
    "id": 82,
    "title": "Line of Sight",
    "thumbnail": "https://www.freetogame.com/g/82/thumbnail.jpg",
    "short_description": "Free FPS game described as Bioshock meets Call of Duty! ",
    "game_url": "https://www.freetogame.com/open/line-of-sight",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "BlackSpot Entertainment",
    "developer": "BlackSpot Entertainment",
    "release_date": "2017-01-31",
    "freetogame_profile_url": "https://www.freetogame.com/line-of-sight"
  },
  {
    "id": 83,
    "title": "Heavy Metal Machines",
    "thumbnail": "https://www.freetogame.com/g/83/thumbnail.jpg",
    "short_description": "A free-to-play multiplayer vehicular combat game based in a post-apocalyptic world.",
    "game_url": "https://www.freetogame.com/open/heavy-metal-machines",
    "genre": "MOBA",
    "platform": "PC (Windows)",
    "publisher": "Hoplon",
    "developer": "Hoplon",
    "release_date": "2017-01-31",
    "freetogame_profile_url": "https://www.freetogame.com/heavy-metal-machines"
  },
  {
    "id": 85,
    "title": "Infestation: The New Z",
    "thumbnail": "https://www.freetogame.com/g/85/thumbnail.jpg",
    "short_description": "A re-work of the open world zombie shooter game Infestation: Survivor Stories (or as it was formerly known The War Z).",
    "game_url": "https://www.freetogame.com/open/infestation-new-z",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "OP Productions LLC",
    "developer": "Fredaikis AB",
    "release_date": "2016-11-22",
    "freetogame_profile_url": "https://www.freetogame.com/infestation-new-z"
  },
  {
    "id": 95,
    "title": "Paladins",
    "thumbnail": "https://www.freetogame.com/g/95/thumbnail.jpg",
    "short_description": "A free-to-play team-based shooter developed and published by Hi-Rez Games, the creators of SMITE. ",
    "game_url": "https://www.freetogame.com/open/paladins",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Hi-Rez Studios",
    "developer": "Hi-Rez Studios",
    "release_date": "2016-09-16",
    "freetogame_profile_url": "https://www.freetogame.com/paladins"
  },
  {
    "id": 108,
    "title": "Zula",
    "thumbnail": "https://www.freetogame.com/g/108/thumbnail.jpg",
    "short_description": "A free-to-play online FPS developed and published by IDC/Games. ",
    "game_url": "https://www.freetogame.com/open/zula",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "IDC/Games",
    "developer": "IDC/Games",
    "release_date": "2016-06-23",
    "freetogame_profile_url": "https://www.freetogame.com/zula"
  },
  {
    "id": 110,
    "title": "UFO Online: Invasion",
    "thumbnail": "https://www.freetogame.com/g/110/thumbnail.jpg",
    "short_description": "A free-to-play post-apocalyptic, turn-based tactical combat MMO developed by Bad Pixel. ",
    "game_url": "https://www.freetogame.com/open/ufo-online-invasion",
    "genre": "MMORPG",
    "platform": "PC (Windows)",
    "publisher": "Bad Pixel",
    "developer": "Bad Pixel",
    "release_date": "2016-06-08",
    "freetogame_profile_url": "https://www.freetogame.com/ufo-online-invasion"
  },
  {
    "id": 118,
    "title": "Starbreak",
    "thumbnail": "https://www.freetogame.com/g/118/thumbnail.jpg",
    "short_description": "A Roguelike MMORPG with MetroidVania-style platformer gameplay! Castlevania and Metroid fans will love this game! ",
    "game_url": "https://www.freetogame.com/open/starbreak",
    "genre": "MMORPG",
    "platform": "PC (Windows), Web Browser",
    "publisher": "Crunchy Games",
    "developer": "Crunchy Games",
    "release_date": "2016-05-10",
    "freetogame_profile_url": "https://www.freetogame.com/starbreak"
  },
  {
    "id": 124,
    "title": "Holodrive",
    "thumbnail": "https://www.freetogame.com/g/124/thumbnail.jpg",
    "short_description": "A free-to-play 2D multiplayer shooter developed by BitCake Studio and published by Versus Evil in which players play as customizable robots or Dummys. ",
    "game_url": "https://www.freetogame.com/open/holodrive",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Versus Evil",
    "developer": "BitCake Studio",
    "release_date": "2016-03-24",
    "freetogame_profile_url": "https://www.freetogame.com/holodrive"
  },
  {
    "id": 134,
    "title": "War Trigger 3",
    "thumbnail": "https://www.freetogame.com/g/134/thumbnail.jpg",
    "short_description": "A MMO shooter with infantry, vehicle, and air combat across massive maps! ",
    "game_url": "https://www.freetogame.com/open/wt3",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Rocketeer Games",
    "developer": "Rocketeer Games",
    "release_date": "2015-12-23",
    "freetogame_profile_url": "https://www.freetogame.com/wt3"
  },
  {
    "id": 137,
    "title": "Metal War Online: Retribution",
    "thumbnail": "https://www.freetogame.com/g/137/thumbnail.jpg",
    "short_description": "A high-speed multiplayer online concept car shooter game with racing elements!",
    "game_url": "https://www.freetogame.com/open/metal-war-online",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "GDT Limited",
    "developer": "GDT Limited",
    "release_date": "2015-12-11",
    "freetogame_profile_url": "https://www.freetogame.com/metal-war-online"
  },
  {
    "id": 222,
    "title": "MechWarrior Online",
    "thumbnail": "https://www.freetogame.com/g/222/thumbnail.jpg",
    "short_description": "A free-to-play PvP game that's a faithful adaptation of the popular MechWarrior strategy board games.",
    "game_url": "https://www.freetogame.com/open/mechwarrior-online",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Piranha Games Inc.",
    "developer": "Piranha Games Inc.",
    "release_date": "2015-12-10",
    "freetogame_profile_url": "https://www.freetogame.com/mechwarrior-online"
  },
  {
    "id": 7,
    "title": "Armored Warfare",
    "thumbnail": "https://www.freetogame.com/g/7/thumbnail.jpg",
    "short_description": "A modern team-based MMO tank game from Obsidian Entertainment.",
    "game_url": "https://www.freetogame.com/open/armored-warfare",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "My.com (Mail.ru Group)",
    "developer": "Obsidian Entertainment",
    "release_date": "2015-10-08",
    "freetogame_profile_url": "https://www.freetogame.com/armored-warfare"
  },
  {
    "id": 149,
    "title": "Americas Army: Proving Grounds",
    "thumbnail": "https://www.freetogame.com/g/149/thumbnail.jpg",
    "short_description": "Take a first person shooter, have the game developed by the U.S. Army and you ve got Americas Army.",
    "game_url": "https://www.freetogame.com/open/americas-army",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "U.S. Army",
    "developer": "U.S. Army",
    "release_date": "2015-10-01",
    "freetogame_profile_url": "https://www.freetogame.com/americas-army"
  },
  {
    "id": 152,
    "title": "WARMODE",
    "thumbnail": "https://www.freetogame.com/g/152/thumbnail.jpg",
    "short_description": "A Free to play multiplayer online shooter. Sight in enemies to master Headshots, Double Kills and Triple Kills! ",
    "game_url": "https://www.freetogame.com/open/warmode",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "WARTEAM",
    "developer": "WARTEAM",
    "release_date": "2015-08-26",
    "freetogame_profile_url": "https://www.freetogame.com/warmode"
  },
  {
    "id": 159,
    "title": "Codename CURE",
    "thumbnail": "https://www.freetogame.com/g/159/thumbnail.jpg",
    "short_description": "A free to play 3D MMOFPS featuring cooperative play, and objective-based missions.",
    "game_url": "https://www.freetogame.com/open/codename-cure",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Hoobalugalar_X",
    "developer": "Hoobalugalar_X",
    "release_date": "2015-07-18",
    "freetogame_profile_url": "https://www.freetogame.com/codename-cure"
  },
  {
    "id": 169,
    "title": "Dirty Bomb",
    "thumbnail": "https://www.freetogame.com/g/169/thumbnail.jpg",
    "short_description": "A free-to-play first person shooter multiplayer game set in a post-apocalyptic London.",
    "game_url": "https://www.freetogame.com/open/dirty-bomb",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Warchest Ltd.",
    "developer": "Splash Damage",
    "release_date": "2015-06-01",
    "freetogame_profile_url": "https://www.freetogame.com/dirty-bomb"
  },
  {
    "id": 173,
    "title": "Block N Load",
    "thumbnail": "https://www.freetogame.com/g/173/thumbnail.jpg",
    "short_description": "A free-to-play multiplayer online shooter game that looks like a mix of Minecraft and Team Fortress 2.",
    "game_url": "https://www.freetogame.com/open/block-n-load",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Jagex",
    "developer": "Jagex, Artplant",
    "release_date": "2015-04-30",
    "freetogame_profile_url": "https://www.freetogame.com/block-n-load"
  },
  {
    "id": 175,
    "title": "Survarium",
    "thumbnail": "https://www.freetogame.com/g/175/thumbnail.jpg",
    "short_description": "A free to play post-apocalyptic online FPS game.",
    "game_url": "https://www.freetogame.com/open/survarium",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Vostok Games",
    "developer": "Vostok Games",
    "release_date": "2015-04-02",
    "freetogame_profile_url": "https://www.freetogame.com/survarium"
  },
  {
    "id": 56,
    "title": "Grimoire: Manastorm",
    "thumbnail": "https://www.freetogame.com/g/56/thumbnail.jpg",
    "short_description": "A free-to-play multiplayer FPS... with wizards. ",
    "game_url": "https://www.freetogame.com/open/grimoire-manastorm",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Omniconnection",
    "developer": "Omniconnection",
    "release_date": "2015-02-04",
    "freetogame_profile_url": "https://www.freetogame.com/grimoire-manastorm"
  },
  {
    "id": 180,
    "title": "Gear Up",
    "thumbnail": "https://www.freetogame.com/g/180/thumbnail.jpg",
    "short_description": "Control your unique tank or robot in multiplayer arcade action!",
    "game_url": "https://www.freetogame.com/open/gear-up",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Doctor Entertainment",
    "developer": "Doctor Entertainment",
    "release_date": "2015-01-29",
    "freetogame_profile_url": "https://www.freetogame.com/gear-up"
  },
  {
    "id": 182,
    "title": "Dungeon Defenders 2",
    "thumbnail": "https://www.freetogame.com/g/182/thumbnail.jpg",
    "short_description": "A free-to-play cooperative 3D tower-defense game by Trendy Entertainment.",
    "game_url": "https://www.freetogame.com/open/dungeon-defenders-2",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Trendy Entertainment",
    "developer": "Trendy Entertainment",
    "release_date": "2014-12-05",
    "freetogame_profile_url": "https://www.freetogame.com/dungeon-defenders-2"
  },
  {
    "id": 184,
    "title": "Blockade 3D",
    "thumbnail": "https://www.freetogame.com/g/184/thumbnail.jpg",
    "short_description": "A free to play FPS in an editable procedural world.",
    "game_url": "https://www.freetogame.com/open/blockade-3d",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Shumkov Dmitriy",
    "developer": "Shumkov Dmitriy",
    "release_date": "2014-11-05",
    "freetogame_profile_url": "https://www.freetogame.com/blockade-3d"
  },
  {
    "id": 186,
    "title": "Double Action",
    "thumbnail": "https://www.freetogame.com/g/186/thumbnail.jpg",
    "short_description": "A free to play FPS with bullet time and stylish kills!",
    "game_url": "https://www.freetogame.com/open/double-action",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Double Action Factory ",
    "developer": "Double Action Factory ",
    "release_date": "2014-10-23",
    "freetogame_profile_url": "https://www.freetogame.com/double-action"
  },
  {
    "id": 188,
    "title": "Counter-Strike Nexon: Studio",
    "thumbnail": "https://www.freetogame.com/g/188/thumbnail.jpg",
    "short_description": "What's better than Counter-Strike? Counter-Strike with more modes and Zombies!",
    "game_url": "https://www.freetogame.com/open/counter-strike-nexon",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Nexon Europe GmbH",
    "developer": "Nexon",
    "release_date": "2014-10-07",
    "freetogame_profile_url": "https://www.freetogame.com/counter-strike-nexon"
  },
  {
    "id": 200,
    "title": "Guns and Robots",
    "thumbnail": "https://www.freetogame.com/g/200/thumbnail.jpg",
    "short_description": "A free to play online third person shooter with massive customization! ",
    "game_url": "https://www.freetogame.com/open/guns-and-robots",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Masthead Studios Ltd, Thegamewallstudios, Gamigo AG",
    "developer": "Masthead Studios Ltd",
    "release_date": "2014-08-05",
    "freetogame_profile_url": "https://www.freetogame.com/guns-and-robots"
  },
  {
    "id": 203,
    "title": "Robocraft",
    "thumbnail": "https://www.freetogame.com/g/203/thumbnail.jpg",
    "short_description": "A free-to-play MMO sandbox building game! ",
    "game_url": "https://www.freetogame.com/open/robocraft",
    "genre": "MMO",
    "platform": "PC (Windows)",
    "publisher": "Freejam",
    "developer": "Freejam",
    "release_date": "2014-07-08",
    "freetogame_profile_url": "https://www.freetogame.com/robocraft"
  },
  {
    "id": 204,
    "title": "Unturned",
    "thumbnail": "https://www.freetogame.com/g/204/thumbnail.jpg",
    "short_description": "A independently developed free-to-play MMO survival game! ",
    "game_url": "https://www.freetogame.com/open/unturned",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Smartly Dressed Games",
    "developer": "Smartly Dressed Games",
    "release_date": "2014-07-08",
    "freetogame_profile_url": "https://www.freetogame.com/unturned"
  },
  {
    "id": 210,
    "title": "Fistful of Frags",
    "thumbnail": "https://www.freetogame.com/g/210/thumbnail.jpg",
    "short_description": "A first person shooter game set in the Wild West! ",
    "game_url": "https://www.freetogame.com/open/fistful-of-frags",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Fistful of Frags Team",
    "developer": "Fistful of Frags Team",
    "release_date": "2014-05-10",
    "freetogame_profile_url": "https://www.freetogame.com/fistful-of-frags"
  },
  {
    "id": 211,
    "title": "GunZ 2: The Second Duel",
    "thumbnail": "https://www.freetogame.com/g/211/thumbnail.jpg",
    "short_description": "A free-to-play multiplayer Third Person Shooter and follow up to the successful GunZ: The Duel. ",
    "game_url": "https://www.freetogame.com/open/gunz-2",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "MAIET Entertainme",
    "developer": "MAIET Entertainme",
    "release_date": "2014-05-01",
    "freetogame_profile_url": "https://www.freetogame.com/gunz-2"
  },
  {
    "id": 213,
    "title": "Archeblade",
    "thumbnail": "https://www.freetogame.com/g/213/thumbnail.jpg",
    "short_description": "A free-to-play PvP-based multiplayer action game based on a Korean Fantasy Novel.",
    "game_url": "https://www.freetogame.com/open/archeblade",
    "genre": "Fighting",
    "platform": "PC (Windows)",
    "publisher": "CodeBrush Games",
    "developer": "CodeBrush Games",
    "release_date": "2014-04-25",
    "freetogame_profile_url": "https://www.freetogame.com/archeblade"
  },
  {
    "id": 405,
    "title": "Pocket Starships",
    "thumbnail": "https://www.freetogame.com/g/405/thumbnail.jpg",
    "short_description": "A free-to-play cross-platform space combat MMO from SPYR games.",
    "game_url": "https://www.freetogame.com/open/pocket-starships",
    "genre": "Strategy",
    "platform": "Web Browser",
    "publisher": "Spyr",
    "developer": "Spyr",
    "release_date": "0000-00-00",
    "freetogame_profile_url": "https://www.freetogame.com/pocket-starships"
  },
  {
    "id": 224,
    "title": "World of Warplanes",
    "thumbnail": "https://www.freetogame.com/g/224/thumbnail.jpg",
    "short_description": "A free-to-play flight combat MMO brought to you by Wargaming.",
    "game_url": "https://www.freetogame.com/open/world-of-warplanes",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Wargaming",
    "developer": "Wargaming",
    "release_date": "2013-11-12",
    "freetogame_profile_url": "https://www.freetogame.com/world-of-warplanes"
  },
  {
    "id": 231,
    "title": "Panzar",
    "thumbnail": "https://www.freetogame.com/g/231/thumbnail.jpg",
    "short_description": "A free-to-play multiplayer third-person shooter with rpg elements and CryEngine 3 powered graphics.",
    "game_url": "https://www.freetogame.com/open/panzar",
    "genre": "MOBA",
    "platform": "PC (Windows)",
    "publisher": "Panzar",
    "developer": "Troxit Service",
    "release_date": "2013-04-12",
    "freetogame_profile_url": "https://www.freetogame.com/panzar"
  },
  {
    "id": 235,
    "title": "Star Conflict",
    "thumbnail": "https://www.freetogame.com/g/235/thumbnail.jpg",
    "short_description": "A free to play action-packed MMO space simulation game.",
    "game_url": "https://www.freetogame.com/open/star-conflict",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Gaijin Entertainment",
    "developer": "Star Gem Inc.",
    "release_date": "2013-02-28",
    "freetogame_profile_url": "https://www.freetogame.com/star-conflict"
  },
  {
    "id": 417,
    "title": "Dino Storm",
    "thumbnail": "https://www.freetogame.com/g/417/thumbnail.jpg",
    "short_description": "A free-to-play 3D MMO with cowboys, dinosaurs, and laser guns.",
    "game_url": "https://www.freetogame.com/open/dino-storm",
    "genre": "MMORPG",
    "platform": "Web Browser",
    "publisher": "Splitscreen S.",
    "developer": "Splits. S",
    "release_date": "2012-09-12",
    "freetogame_profile_url": "https://www.freetogame.com/dino-storm"
  },
  {
    "id": 24,
    "title": "Counter-Strike: Global Offensive",
    "thumbnail": "https://www.freetogame.com/g/24/thumbnail.jpg",
    "short_description": "The popular multiplayer shooter from Valve. ",
    "game_url": "https://www.freetogame.com/open/counter-strike-global-offensive",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Valve",
    "developer": "Valve, Hidden Path Entertainment",
    "release_date": "2012-08-21",
    "freetogame_profile_url": "https://www.freetogame.com/counter-strike-global-offensive"
  },
  {
    "id": 453,
    "title": "Gotham City Impostors",
    "thumbnail": "https://www.freetogame.com/g/453/thumbnail.jpg",
    "short_description": "A free to play multiplayer FPS that pits vigilantes dressed up like Batman against criminals dressed up like the Joker",
    "game_url": "https://www.freetogame.com/open/gotham-city-impostors",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Warner Bros. Interactive Entertainment",
    "developer": "Monolith Productions, Inc.",
    "release_date": "2012-08-31",
    "freetogame_profile_url": "https://www.freetogame.com/gotham-city-impostors"
  },
  {
    "id": 256,
    "title": "Realm of the Mad God",
    "thumbnail": "https://www.freetogame.com/g/256/thumbnail.jpg",
    "short_description": "A fast paced 2d free to play MMO shooter game with a retro 8-bit style.",
    "game_url": "https://www.freetogame.com/open/realm-mad-god",
    "genre": "MMORPG",
    "platform": "PC (Windows), Web Browser",
    "publisher": "Kabam",
    "developer": "Wild Shadow Studios",
    "release_date": "2012-02-21",
    "freetogame_profile_url": "https://www.freetogame.com/realm-mad-god"
  },
  {
    "id": 261,
    "title": "No More Room in Hell",
    "thumbnail": "https://www.freetogame.com/g/261/thumbnail.jpg",
    "short_description": "A free to play cooperative FPS survival horror mod for the Source Engine.",
    "game_url": "https://www.freetogame.com/open/no-more-room-in-hell",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Lever Games",
    "developer": "No More Room in Hell Team",
    "release_date": "2011-10-31",
    "freetogame_profile_url": "https://www.freetogame.com/no-more-room-in-hell"
  },
  {
    "id": 267,
    "title": "Mission Against Terror",
    "thumbnail": "https://www.freetogame.com/g/267/thumbnail.jpg",
    "short_description": "A free to play fast-paced lobby-based MMOFPS with lots of game modes and tons of weapons.",
    "game_url": "https://www.freetogame.com/open/mat",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Suba Games",
    "developer": "Kingsoft",
    "release_date": "2011-07-08",
    "freetogame_profile_url": "https://www.freetogame.com/mat"
  },
  {
    "id": 423,
    "title": "Steel Legions",
    "thumbnail": "https://www.freetogame.com/g/423/thumbnail.jpg",
    "short_description": "A free to play 3d browser based tank game with fast-paced tactical battles! ",
    "game_url": "https://www.freetogame.com/open/steel-legions",
    "genre": "Shooter",
    "platform": "Web Browser",
    "publisher": "Splitscreen Studios",
    "developer": "Splitscreen Studios",
    "release_date": "2011-06-15",
    "freetogame_profile_url": "https://www.freetogame.com/steel-legions"
  },
  {
    "id": 60,
    "title": "Brink",
    "thumbnail": "https://www.freetogame.com/g/60/thumbnail.jpg",
    "short_description": "A free-to-play first-person-shoot developed by Splash Damage and published by Bethesda Softworks. ",
    "game_url": "https://www.freetogame.com/open/brink",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Bethesda Softworks",
    "developer": "Splash Damage",
    "release_date": "2011-05-09",
    "freetogame_profile_url": "https://www.freetogame.com/brink"
  },
  {
    "id": 258,
    "title": "APB Reloaded",
    "thumbnail": "https://www.freetogame.com/g/258/thumbnail.jpg",
    "short_description": "A free to play 3D MMO third person shooter game brought to you by GTA creator.",
    "game_url": "https://www.freetogame.com/open/apb",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Reloaded Games",
    "developer": "Reloaded Productions",
    "release_date": "2010-06-29",
    "freetogame_profile_url": "https://www.freetogame.com/apb"
  },
  {
    "id": 280,
    "title": "WolfTeam",
    "thumbnail": "https://www.freetogame.com/g/280/thumbnail.jpg",
    "short_description": "A free to play MMOFPS with a twist.",
    "game_url": "https://www.freetogame.com/open/wolfteam",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Aeria Games",
    "developer": "Softnyx",
    "release_date": "2009-07-09",
    "freetogame_profile_url": "https://www.freetogame.com/wolfteam"
  },
  {
    "id": 291,
    "title": "theHunter",
    "thumbnail": "https://www.freetogame.com/g/291/thumbnail.jpg",
    "short_description": "An MMO shooter where players can hunt 22 different animals in various locations.",
    "game_url": "https://www.freetogame.com/open/thehunter",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Expansive Worlds , Avalanche Studios",
    "developer": "Expansive Worlds , Avalanche Studios",
    "release_date": "2009-03-05",
    "freetogame_profile_url": "https://www.freetogame.com/thehunter"
  },
  {
    "id": 319,
    "title": "Ace Online",
    "thumbnail": "https://www.freetogame.com/g/319/thumbnail.jpg",
    "short_description": "A free to play fast action 3D sci-fi MMO where players control space fighters jets.",
    "game_url": "https://www.freetogame.com/open/ace-online",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Suba Games",
    "developer": "MasangSoft",
    "release_date": "2008-08-29",
    "freetogame_profile_url": "https://www.freetogame.com/ace-online"
  },
  {
    "id": 310,
    "title": "Team Fortress 2",
    "thumbnail": "https://www.freetogame.com/g/310/thumbnail.jpg",
    "short_description": "Valve's iconic class-based free-to-play first-person shooter!",
    "game_url": "https://www.freetogame.com/open/team-fortress-2",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Valve",
    "developer": "Valve",
    "release_date": "2007-10-10",
    "freetogame_profile_url": "https://www.freetogame.com/team-fortress-2"
  },
  {
    "id": 15,
    "title": "Crossfire",
    "thumbnail": "https://www.freetogame.com/g/15/thumbnail.jpg",
    "short_description": "A first person tactical shooter with a huge selection of game modes!",
    "game_url": "https://www.freetogame.com/open/crossfire",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Neowiz Games",
    "developer": "SmileGate",
    "release_date": "2007-05-03",
    "freetogame_profile_url": "https://www.freetogame.com/crossfire"
  },
  {
    "id": 313,
    "title": "Teeworlds",
    "thumbnail": "https://www.freetogame.com/g/313/thumbnail.jpg",
    "short_description": "A free to play retro multiplayer online shooter where you can even design your own maps!",
    "game_url": "https://www.freetogame.com/open/teeworlds",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Teeworlds Team ",
    "developer": "Teeworlds Team ",
    "release_date": "2007-05-27",
    "freetogame_profile_url": "https://www.freetogame.com/teeworlds"
  }
]`)
export default GamesDB
